version: '3.9'

services:
  uidemo:
      stdin_open: true
      container_name: uidemo-container-demo
      image: "uidemo-image-demo"
      build:
        context: .
        dockerfile: Dockerfile
      environment:
      - CHOKIDAR_USEPOLLING=true
      restart: always
      volumes:
        - '.:/uidemo'
        - '/uidemo/node_modules'
      ports:
        - "8001:5173"
