version: "3.7"

name: "video"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: backend
    container_name: backend
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    env_file: .env
    volumes:
        - ../:/src
        - ../../data/archive/TrainValVideo:/data
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true