version: '3.7'

name: "database"

services:
  postgresdb:
    image: ankane/pgvector
    container_name: database
    restart: unless-stopped
    env_file: .env.database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=500"]
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres-data:
    driver: local
